# Generated by Django 5.1.5 on 2025-03-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_eventmodel_alter_assosiationmembersmodel_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='Roll_num',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
