# Generated by Django 5.1.5 on 2025-03-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_roll_num_studentmodel_rollnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='status',
            new_name='place',
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='organizer',
            field=models.CharField(max_length=100),
        ),
    ]
