# Generated by Django 5.1.5 on 2025-03-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_badgemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='CC',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='CurrentArrear',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='Mentor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='cgpa',
            field=models.FloatField(null=True),
        ),
    ]
