# Generated by Django 5.1.5 on 2025-03-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_studentmodel_cc_studentmodel_currentarrear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='award',
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='proofAttachment',
            field=models.FileField(blank=True, null=True, upload_to='Certificates'),
        ),
    ]
