# Generated by Django 5.1.5 on 2025-03-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_eventmodel_award_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
