# Generated by Django 5.1.5 on 2025-04-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_teachermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('Section', models.CharField(max_length=1)),
                ('RollNum', models.TextField()),
                ('CC', models.CharField(max_length=10)),
                ('Mentor1', models.CharField(max_length=10)),
                ('Mentor2', models.CharField(max_length=10, null=True)),
                ('Mentor3', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
