# Generated by Django 5.1.5 on 2025-04-01 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='ClassModel',
        ),
    ]
