# Generated by Django 5.1.5 on 2025-04-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_class_classmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='CurrentArrear',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='batch',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='phoneNum',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='ProfilePic'),
        ),
    ]
