# Generated by Django 5.1.5 on 2025-04-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_studentmodel_currentarrear_studentmodel_batch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classmodel',
            old_name='Mentor1',
            new_name='mentor1',
        ),
        migrations.RenameField(
            model_name='classmodel',
            old_name='RollNum',
            new_name='rollNum',
        ),
        migrations.RenameField(
            model_name='classmodel',
            old_name='Section',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='classmodel',
            old_name='Year',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='classmodel',
            name='Mentor2',
        ),
        migrations.RemoveField(
            model_name='classmodel',
            name='Mentor3',
        ),
        migrations.AddField(
            model_name='classmodel',
            name='mentor2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='mentor3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
