# Generated by Django 5.1.5 on 2025-04-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_mentor1_classmodel_mentor1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='email',
        ),
    ]
