# Generated by Django 5.1.5 on 2025-04-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_studentmodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POId', models.CharField(max_length=10)),
                ('title', models.CharField(blank=True, max_length=35, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
