# Generated by Django 5.1.5 on 2025-04-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_objective'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='objective',
            new_name='objectiveModel',
        ),
    ]
