# Generated by Django 5.1.5 on 2025-04-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_objectivemodel_poid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventShowcaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='Assosation-Events')),
            ],
        ),
    ]
