# Generated by Django 5.1.5 on 2025-04-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_assosationprogrammodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assosiationmembersmodel',
            old_name='Desigination',
            new_name='desigination',
        ),
        migrations.RenameField(
            model_name='assosiationmembersmodel',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='assosiationmembersmodel',
            old_name='ProfilePic',
            new_name='profilePic',
        ),
        migrations.RenameField(
            model_name='assosiationmembersmodel',
            old_name='Year',
            new_name='year',
        ),
        migrations.AddField(
            model_name='assosiationmembersmodel',
            name='acadmaicYear',
            field=models.TextField(null=True),
        ),
    ]
