# Generated by Django 5.1.5 on 2025-04-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_desigination_assosiationmembersmodel_desigination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assosiationmembersmodel',
            name='acadmaicYear',
            field=models.TextField(),
        ),
    ]
