# Generated by Django 5.1.5 on 2025-04-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_assosiationmembersmodel_acadmaicyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assosiationmembersmodel',
            name='acadmaicYear',
            field=models.CharField(max_length=12),
        ),
    ]
