# Generated by Django 5.1.5 on 2025-04-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_assosiationmembersmodel_acadmaicyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assosiationmembersmodel',
            name='desigination',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='assosiationmembersmodel',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='student',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='placementmodel',
            name='Name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='CC',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='Mentor',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='Name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
